### ISSUE TITLE
twarc client error

### ISSUE THREAD

**Issue by ryanboyd** [echen102/COVID-19-TweetIDs#38]
In the most recent update, there appears to be a tweet that belongs to an account that has since been locked (although I'm not sure about this). The hydrate script fails on `2021-10\coronavirus-tweet-id-2021-10-15-00.txt` and throws the following exception:

```
WARNING:twarc:401 Authentication required for https://api.twitter.com/1.1/statuses/lookup.json
 27%|████████████████████▎                                                      | 22665/83672 [03:21<09:01, 112.62it/s]
Traceback (most recent call last):
  File "F:\COVID-19-TweetIDs-pulled\hydrate.py", line 70, in <module>
    main()
  File "F:\COVID-19-TweetIDs-pulled\hydrate.py", line 30, in main
    hydrate(path)
  File "F:\COVID-19-TweetIDs-pulled\hydrate.py", line 61, in hydrate
    for tweet in twarc.hydrate(id_file.open()):
  File "C:\Users\Ryan\AppData\Local\Programs\Python\Python39\lib\site-packages\twarc\client.py", line 606, in hydrate
    resp = self.post(
  File "C:\Users\Ryan\AppData\Local\Programs\Python\Python39\lib\site-packages\twarc\decorators.py", line 31, in new_f
    resp.raise_for_status()
  File "C:\Users\Ryan\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://api.twitter.com/1.1/statuses/lookup.json
This is a protected or locked account, or the credentials provided are no longer valid.
```

**Comment by echen102** [comment]
Hi @ryanboyd ! If you skip this particular tweet, are you able to hydrate the rest of the file?

**Comment by echen102** [comment]
(This seems to be Twarc passing on a 401 error that they receive from Twitter's API when trying to fetch this tweet by it's ID -- see https://github.com/DocNow/twarc/blob/main/twarc/decorators.py) Are you using your Twitter API credentials anywhere else?
